# Generated by Django 3.1.7 on 2021-03-23 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='desc',
            new_name='feedback',
        ),
    ]
