# Generated by Django 3.1.7 on 2021-03-23 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20210324_0206'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='msg',
            new_name='sgm',
        ),
    ]
