# Generated by Django 3.1.7 on 2021-05-01 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_registration'),
    ]

    operations = [
        migrations.CreateModel(
            name='menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_name', models.CharField(max_length=50)),
                ('menu_desc', models.CharField(max_length=50)),
                ('menu_price', models.CharField(max_length=50)),
            ],
        ),
    ]
