# Generated by Django 3.1.7 on 2021-05-01 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='photo',
            field=models.ImageField(default='NA', upload_to='media/recepies'),
        ),
    ]
