# Generated by Django 3.1.7 on 2021-05-06 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_auto_20210506_2040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='bnme',
            new_name='bname',
        ),
    ]
